package vlsu.ProducerCentr.serverside.utils.exception;

public enum ErrorCode {
    SUCH_LOGIN_ALREADY_EXISTS,
    WRONG_LOGIN_FORM,
    WRONG_PASSWORD_FORM,
    WRONG_CREDENTIALS,
    UNEXPECTED_TEST_EXTERNAL_ID,
    UNEXPECTED_LANGUAGE_CODE,
    NOT_EMAIL,
    UNEXPECTED_GENDER,
    UNEXPECTED_ANSWER_EXTERNAL_ID,
    UNEXPECTED_QUESTION_EXTERNAL_ID,
    END_DATE_IS_BEFORE_START_DATE,
    SAME_RESULT_BORDERS,
    NO_SUCH_TEST_IN_SUCH_LANGUAGE,
    NOT_YOUR_CLIENT;
}
